<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" name="CheckingCriticalFailures" tests="3" failures="1" timestamp="13 Jul 2015 11:06:54 GMT" time="0.008" errors="0">
  <testcase name="SubstactionTest" time="0.001" classname="com.comarch.training.FailingCases">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
	at com.comarch.training.FailingCases.SubstactionTest(FailingCases.java:57)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- SubstactionTest -->
  <testcase name="AddingToMemoryTest" time="0.0" classname="com.comarch.training.FailingCases">
    <skipped/>
  </testcase> <!-- AddingToMemoryTest -->
  <testcase name="DivisionTest" time="0.0" classname="com.comarch.training.FailingCases">
    <skipped/>
  </testcase> <!-- DivisionTest -->
</testsuite> <!-- CheckingCriticalFailures -->
